In [3]:
from keras.datasets import mnist
(X0, Y0), (X1, Y1) = mnist.load_data()
print(X0.shape)

(60000, 28, 28)


In [4]:
from matplotlib import pyplot as plt
plt.figure()
fig, ax = plt.subplots(2, 5)
ax = ax.flatten()
for i in range(10):
    Im = X0[Y0 == i][0]
    ax[i].imshow(Im)
plt.show()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 10 Axes>

In [5]:
# 数据预处理
from keras.utils import np_utils
N0 = X0.shape[0]
N1 = X1.shape[0]
print([N0, N1])
X0 = X0.reshape(N0, 28, 28, 1) / 255
X1 = X1.reshape(N1, 28, 28, 1) / 255
YY0 = np_utils.to_categorical(Y0) # 变为 one_hot 形式
YY1 = np_utils.to_categorical(Y1)
print(YY1)

[60000, 10000]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
# LeNet-5 模型搭建
from keras.layers import Conv2D, Dense, Flatten, Input, MaxPooling2D
from keras import Model

# 输入层
input_layer = Input([28, 28, 1])
x = input_layer
# 卷积层，6个大小为5*5的卷积核进行padding=same的操作，激活函数为ReLU
x = Conv2D(6, [5, 5], padding="same", activation="relu")(x)
# 池化层
x = MaxPooling2D(pool_size=[2, 2], strides=[2, 2])(x)
# 卷积层
x = Conv2D(16, [5, 5], padding="valid", activation="relu")(x)
# 池化层
x = MaxPooling2D(pool_size=[2, 2], strides=[2, 2])(x)
# 拉直
x = Flatten()(x)
# 全连接层
x = Dense(120, activation="relu")(x)
x = Dense(84, activation="relu")(x)
x = Dense(10, activation="softmax")(x)
# 输出层
output_layer = x
model = Model(input_layer, output_layer)
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 28, 28, 1)]       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 28, 28, 6)         156       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 10, 10, 16)        2416      
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 16)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 400)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 120)              

In [7]:
# LetNet-5 编译运行
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy'])
model.fit(X0, YY0, epochs=10, batch_size=200, validation_data=[X1, YY1])

Epoch 1/10
300/300 [==============================] - 23s 77ms/step - loss: 0.3729 - accuracy: 0.8928 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/10
300/300 [==============================] - 26s 85ms/step - loss: 0.1049 - accuracy: 0.9690 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 3/10
300/300 [==============================] - 26s 87ms/step - loss: 0.0692 - accuracy: 0.9786 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 4/10
300/300 [==============================] - 27s 89ms/step - loss: 0.0549 - accuracy: 0.9826 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 5/10
300/300 [==============================] - 27s 90ms/step - loss: 0.0467 - accuracy: 0.9856 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 6/10
300/300 [==============================] - 27s 90ms/step - loss: 0.0391 - accuracy: 0.9877 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 7/10
300/300 [==============================] - 27s 90ms/step - loss: 0.0340 - acc